services:
  turnstile.type:
    class: PixelOpen\CloudflareTurnstileBundle\Type\TurnstileType
    tags: ['form.type']
    arguments:
      $key: '%pixelopen_cloudflare_turnstile.key%'
      $enable: '%pixelopen_cloudflare_turnstile.enable%'
  turnstile.validator:
    class: PixelOpen\CloudflareTurnstileBundle\Validator\CloudflareTurnstileValidator
    tags: ['validator.constraint_validator']
    arguments:
      $enable: '%pixelopen_cloudflare_turnstile.enable%'
      $turnstileHttpClient: '@turnstile.http_client'
    autowire: true
  turnstile.http_client:
    class: PixelOpen\CloudflareTurnstileBundle\Http\CloudflareTurnstileHttpClient
    arguments:
      $secret: '%pixelopen_cloudflare_turnstile.secret%'
    autowire: true
